### PR TITLE
Add ability to create multiple direct messages at different classification levels (Issue 68)

### PR DESCRIPTION
**Pull request by douglasrapp**
Modified the back-end to allow the creation of multiple direct messages with the same person.

Modified the 'room' publication to work with more than a single room id. In the case that no room id is specified when subscribing, all rooms to which the user has access will be returned.

Added subscription to all of the users rooms to the FlowRouter subscription list. This allows the client to hold subscriptions to all of their joined rooms in addition to all of their chat subscriptions.

Added logic on the client-side to obtain security banner data for displaying both in the side panel (next to any 'duplicate' direct messages) as well as in the alt-text when hovering the mouse. In the case of the banner text in the side panel, an abbreviated version of the banner text is used, so as to save space.

For example, instead of displaying:

> UNCLASSIFIED // BP // NOFORN

It will display:

> U / BP/ USA

The banner text in the alt-text remains the full string. This logic was added to the 'getSecurityBanner' method.

### CODE REVIEW

**Comment by rwakida** [comment]
Should we allow multiple conversations between the 2 users WITH the same labels?  or should there only be one conversation with the same label?  e.g. can testuser1 and testadmin have 2 direct message conversations at the U/USA level?

dm

**Comment by douglasrapp** [comment]
Good point. I think if a dm with the same person exists with the same label set, it shouldn't create a new one. But what should be the behavior when that happens? Should the user get presented with an error, or should it just automatically open the existing dm?

**Comment by rwakida** [comment]
I think it should automatically open.

**Comment by bbrockman** [comment]
ditto

**Comment by douglasrapp** [comment]
Done. Added a check to the 'createDirectMessage' method to first try to find a dm with the same users and access permissions. If it finds one, it just returns that existing room id, otherwise, it creates a new dm.

**Comment by berkich** [comment]
:+1:

**Comment by douglasrapp** [comment]
Fixed 2 bugs:

1) When user A created multiple direct messages with user B, user A would see the banner data in the left panel, but user B would not. This was due to trying to match an array with the wrong order (e.g., `['testuser1', 'testuser2'] != ['testuser2', 'testuser1']`), so detecting multiple messages with the same person was failing.

2) When attempting to create a 'new' direct message with the same user and the same permissions as an existing message, it wasn't creating a new one (good), but it wasn't opening the existing one (bad). The problem was when an existing one was detected, it was erroneously returning the entire room document instead of the id, so the FlowRouter didn't know what to do with it. The result was a blank white screen in the chat area.

**Comment by rwakida** [comment]
:+1:

**Comment by douglasrapp** [comment]
Working on merging from the master branch. Apparently this branch was created before the most recent upstream merge. So, with the friendly URLs, multiple direct messages with same user have been broken. Need to think about how to modify those URLs...

**Comment by douglasrapp** [comment]
For direct messages, I added the room id back to the URL to allow the application to differentiate multiple convos with the same user. So, for example, the following:

`http://host:3000/direct/testuser1`

has been replaced by:

`http://host:3000/direct/testuser1/<some hash>`

The resulting URL isn't as "friendly", but it makes sure each conversation has a unique URL for the router to use.

**Comment by rwakida** [comment]
sounds good to me :+1:

**Pull request merged**
