### PR TITLE
All users should belong to the "general" and their location channels after LDAP import.

### PR DESCRIPTION
**Pull request by rwakida**

### CODE REVIEW

**Comment by bbrockman** [comment]
Works good.  It is weird to hit the x on a channel that is a favorite.  It dissapears from Channels, but not favorites.

**Comment by bbrockman** [comment]
Logged in as 2 different users and their Channel / Favorite was populated.

**Comment by bbrockman** [comment]
:+1:

**Comment by rwakida** [comment]
fix #57

**Pull request merged**
